services:
  # Frontend - Next.js with TypeScript and shadcn/ui
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:22-alpine
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_PUBLIC_WS_URL=ws://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # Run stable dev to avoid Turbopack panic from spaces in host path
    command: ["npm", "run", "dev:stable"]
    depends_on:
      backend:
        condition: service_started
    networks:
      - ai-cfo-network
    restart: unless-stopped

  # Backend - FastAPI Gateway with MCP integration
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - KIMI_API_KEY=${KIMI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - TIDB_HOST=${TIDB_HOST}
      - TIDB_USER=${TIDB_USER}
      - TIDB_PASSWORD=${TIDB_PASSWORD}
      - TIDB_DATABASE=${TIDB_DATABASE}
      - TIDB_PORT=${TIDB_PORT}
      - TIDB_MCP_SERVER_URL=http://tidb-mcp-server:8000
      - USE_MCP_CLIENT=true
    volumes:
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      tidb-mcp-server:
        condition: service_started
    networks:
      - ai-cfo-network
    restart: unless-stopped

  # NLP Agent with KIMI Integration
  nlp-agent:
    build:
      context: .
      dockerfile: agents/nlp-agent/Dockerfile
    ports:
      - "8002:8001"
    env_file:
      - .env
    environment:
      - KIMI_API_KEY=${KIMI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    # Remove volumes mount to avoid permission issues
    # volumes:
    #   - ./agents/nlp-agent:/app
    #   - ./config:/app/config
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ai-cfo-network
    restart: unless-stopped

  # Data Agent with TiDB MCP Integration
  data-agent:
    build:
      context: ./agents/data-agent
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - TIDB_HOST=${TIDB_HOST}
      - TIDB_USER=${TIDB_USER}
      - TIDB_PASSWORD=${TIDB_PASSWORD}
      - TIDB_DATABASE=${TIDB_DATABASE}
      - TIDB_PORT=${TIDB_PORT}
      - USE_MCP_CLIENT=true
      - TIDB_MCP_SERVER_URL=http://tidb-mcp-server:8000
      - BACKEND_URL=http://backend:8001
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      tidb-mcp-server:
        condition: service_started
    networks:
      - ai-cfo-network
    restart: unless-stopped

  # Visualization Agent
  viz-agent:
    build:
      context: ./agents/viz-agent
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    # Remove volumes mount to avoid permission issues
    # volumes:
    #   - ./agents/viz-agent:/app
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ai-cfo-network
    restart: unless-stopped

  # TiDB MCP Server
  tidb-mcp-server:
    build:
      context: ./tidb-mcp-server
      dockerfile: Dockerfile
    container_name: tidb-mcp-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # TiDB Connection (required - set in .env file)
      - TIDB_HOST=${TIDB_HOST}
      - TIDB_PORT=${TIDB_PORT:-4000}
      - TIDB_USER=${TIDB_USER}
      - TIDB_PASSWORD=${TIDB_PASSWORD}
      - TIDB_DATABASE=${TIDB_DATABASE}
      - TIDB_SSL_CA=${TIDB_SSL_CA:-}
      - TIDB_SSL_VERIFY_CERT=${TIDB_SSL_VERIFY_CERT:-true}
      - TIDB_SSL_VERIFY_IDENTITY=${TIDB_SSL_VERIFY_IDENTITY:-true}

      # MCP Server Configuration
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-tidb-mcp-server}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-0.1.0}
      - MCP_MAX_CONNECTIONS=${MCP_MAX_CONNECTIONS:-10}
      - MCP_REQUEST_TIMEOUT=${MCP_REQUEST_TIMEOUT:-30}

      # Cache Configuration
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-1000}

      # Security Configuration
      - MAX_QUERY_TIMEOUT=${MAX_QUERY_TIMEOUT:-30}
      - MAX_SAMPLE_ROWS=${MAX_SAMPLE_ROWS:-100}
      - RATE_LIMIT_RPM=${RATE_LIMIT_RPM:-60}

      # HTTP API Configuration
      - USE_HTTP_API=${USE_HTTP_API:-true}

      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    ports:
      - "8000:8000"  # Expose HTTP API port
    volumes:
      # Mount logs directory for persistence
      - ./tidb-mcp-server/logs:/app/logs
      # Mount SSL certificates if needed
      - ${SSL_CERT_PATH:-/dev/null}:/app/certs:ro
    networks:
      - ai-cfo-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s

  # Personalization Agent
  # personal-agent:
  #   build:
  #     context: ./agents/personal-agent
  #     dockerfile: Dockerfile
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #     - DATABASE_URL=${DATABASE_URL}
  #     - TIDB_HOST=${TIDB_HOST}
  #     - TIDB_USER=${TIDB_USER}
  #     - TIDB_PASSWORD=${TIDB_PASSWORD}
  #     - TIDB_DATABASE=${TIDB_DATABASE}
  #     - TIDB_PORT=${TIDB_PORT}
  #   # Remove volumes mount to avoid permission issues
  #   # volumes:
  #   #   - ./agents/personal-agent:/app
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - ai-cfo-network
  #   restart: unless-stopped

  # Redis for MCP Context Store and Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-cfo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s
    restart: unless-stopped

  # RabbitMQ for A2A Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai-cfo-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s
    restart: unless-stopped

  # TiDB Database - DISABLED: Using TiDB Cloud instead
  # tidb:
  #   image: pingcap/tidb:latest
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - TIDB_PASSWORD=${TIDB_PASSWORD}
  #   volumes:
  #     - tidb_data:/var/lib/tidb
  #     - ./config/tidb-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  #     - ./scripts/tidb-healthcheck.sh:/usr/local/bin/tidb-healthcheck.sh:ro
  #   networks:
  #     - ai-cfo-network
  #   healthcheck:
  #     test: ["CMD", "bash", "/usr/local/bin/tidb-healthcheck.sh"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 60s
  #   restart: unless-stopped

volumes:
  redis_data:
  rabbitmq_data:
  tidb_data:

networks:
  ai-cfo-network:
    driver: bridge
