[project]
name = "system-tests"
version = "0.1.0"
description = "System tests for Multi-Agent BI System"
dependencies = [
    "aiohttp>=3.9.0",
    "requests>=2.31.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
